name: html update

on:
  schedule:
  - cron: "10 3-9/2 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.LUNCH_LIST_ACCESS_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - id: run_update
      name: Run menu update
      run: |
        python scraper.py
        git config --global user.name 'anttimc'
        git config --global user.email 'anttimc@users.noreply.github.com'
        git add index.html
        git commit -m "Daily lunch" || exit 0
        git push
